export default {
    FETCH_CONTACTS_START:"FETCH_CONTACTS_START",
    FETCH_CONTACTS_SUCCESS:"FETCH_CONTACTS_SUCCESS",
    FETCH_CONTACTS_ERROR:"FETCH_CONTACTS_ERROR",
    CREATE_CONTACTS_START:"CREATE_CONTACTS_START",
    CREATE_CONTACTS_SUCCESS:"CREATE_CONTACTS_SUCCESS",
    CREATE_CONTACTS_ERROR:"CREATE_CONTACTS_ERROR",
    SET_LIMIT:'SET_LIMIT',
    SET_OFFSET:'SET_OFFSET'
}